#!/usr/bin/env bash
# init.sh — SDD Agent Harness Project Setup
# Interactive script to configure a new project from the template.
# Generates prompt.md for the agent to finish configuration.

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo ""
echo -e "${CYAN}🚀 SDD Agent Harness — Project Setup${NC}"
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ── Project Identity ──
echo -e "${GREEN}📝 Project Identity${NC}"

read -rp "  Project name (kebab-case, e.g. my-app): " PROJECT_NAME
while [ -z "$PROJECT_NAME" ]; do
  echo -e "  ${RED}Project name is required.${NC}"
  read -rp "  Project name (kebab-case, e.g. my-app): " PROJECT_NAME
done

read -rp "  One-line description: " PROJECT_DESC
while [ -z "$PROJECT_DESC" ]; do
  echo -e "  ${RED}Description is required.${NC}"
  read -rp "  One-line description: " PROJECT_DESC
done

echo ""
echo -e "  ${YELLOW}Project type:${NC}"
echo "    1) web-app"
echo "    2) api"
echo "    3) full-stack"
echo "    4) cli"
echo "    5) mobile"
echo "    6) desktop"
read -rp "  Select [1-6] (default: 3): " TYPE_NUM
case "$TYPE_NUM" in
  1) PROJECT_TYPE="web-app" ;;
  2) PROJECT_TYPE="api" ;;
  3) PROJECT_TYPE="full-stack" ;;
  4) PROJECT_TYPE="cli" ;;
  5) PROJECT_TYPE="mobile" ;;
  6) PROJECT_TYPE="desktop" ;;
  *) PROJECT_TYPE="full-stack" ;;
esac

echo ""
echo -e "  ${YELLOW}UI language:${NC}"
echo "    1) English"
echo "    2) Spanish"
echo "    3) Multi-language"
read -rp "  Select [1-3] (default: 1): " LANG_NUM
case "$LANG_NUM" in
  1) UI_LANG="English" ;;
  2) UI_LANG="Spanish" ;;
  3) UI_LANG="Multi-language" ;;
  *) UI_LANG="English" ;;
esac

# ── Stack ──
echo ""
echo -e "${GREEN}🛠 Stack${NC}"

echo ""
echo -e "  ${YELLOW}Frontend framework:${NC}"
echo "    1) Next.js"
echo "    2) Astro"
echo "    3) React (Vite)"
echo "    4) Vue"
echo "    5) Svelte"
echo "    6) None (no frontend)"
read -rp "  Select [1-6] (default: 1): " FE_NUM
case "$FE_NUM" in
  1) FRONTEND="Next.js" ;;
  2) FRONTEND="Astro" ;;
  3) FRONTEND="React (Vite)" ;;
  4) FRONTEND="Vue" ;;
  5) FRONTEND="Svelte" ;;
  6) FRONTEND="None" ;;
  *) FRONTEND="Next.js" ;;
esac

echo ""
echo -e "  ${YELLOW}Backend technology:${NC}"
echo "    1) Node/Express"
echo "    2) Python/FastAPI"
echo "    3) PocketBase"
echo "    4) Supabase"
echo "    5) Go"
echo "    6) Rust"
echo "    7) None (no backend)"
read -rp "  Select [1-7] (default: 1): " BE_NUM
case "$BE_NUM" in
  1) BACKEND="Node/Express" ;;
  2) BACKEND="Python/FastAPI" ;;
  3) BACKEND="PocketBase" ;;
  4) BACKEND="Supabase" ;;
  5) BACKEND="Go" ;;
  6) BACKEND="Rust" ;;
  7) BACKEND="None" ;;
  *) BACKEND="Node/Express" ;;
esac

echo ""
echo -e "  ${YELLOW}Database:${NC}"
echo "    1) PostgreSQL"
echo "    2) SQLite"
echo "    3) MongoDB"
echo "    4) None (no database)"
read -rp "  Select [1-4] (default: 1): " DB_NUM
case "$DB_NUM" in
  1) DATABASE="PostgreSQL" ;;
  2) DATABASE="SQLite" ;;
  3) DATABASE="MongoDB" ;;
  4) DATABASE="None" ;;
  *) DATABASE="PostgreSQL" ;;
esac

echo ""
echo -e "  ${YELLOW}Deploy platform:${NC}"
echo "    1) Docker"
echo "    2) Vercel"
echo "    3) Coolify"
echo "    4) Railway"
echo "    5) Manual"
read -rp "  Select [1-5] (default: 1): " DEP_NUM
case "$DEP_NUM" in
  1) DEPLOY="Docker" ;;
  2) DEPLOY="Vercel" ;;
  3) DEPLOY="Coolify" ;;
  4) DEPLOY="Railway" ;;
  5) DEPLOY="Manual" ;;
  *) DEPLOY="Docker" ;;
esac

# ── Generate prompt.md ──
echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Generating prompt.md...${NC}"

ARCHITECT_NAME="${PROJECT_NAME}-architect"
STACK_SUMMARY="${FRONTEND} + ${BACKEND} + ${DATABASE}"

cat > prompt.md << EOF
# Project Configuration — Generated by init.sh

## Project Identity
- **Name:** ${PROJECT_NAME}
- **Description:** ${PROJECT_DESC}
- **Type:** ${PROJECT_TYPE}
- **UI Language:** ${UI_LANG}

## Stack
- **Frontend:** ${FRONTEND}
- **Backend:** ${BACKEND}
- **Database:** ${DATABASE}
- **Deploy:** ${DEPLOY}
- **Stack Summary:** ${STACK_SUMMARY}

## Agent Configuration
- **Architect Name:** ${ARCHITECT_NAME}

---

## Instructions for Agent

Read this file and execute the following steps:

1. **Rename agent files:**
   - Rename \`.opencode/agents/project-architect.md\` to \`.opencode/agents/${ARCHITECT_NAME}.md\`
   - Update the frontmatter \`name:\` field in the renamed file

2. **Update AGENTS.md:**
   - Fill header placeholders: PROJECT_NAME, ONE_LINE_DESCRIPTION, STACK_TECH, DATE
   - Update the architect name in the Agent Harness table
   - Update the Project Clarification examples if needed

3. **Update opencode config:**
   - Set \`default_agent\` to \`${ARCHITECT_NAME}\` in both \`opencode.json\` and \`opencode.jsonc\`

4. **Configure agents for this stack:**
   - If Frontend is "None": delete \`frontend-developer.md\`
   - If Backend is "None": delete \`backend-developer.md\`
   - Keep \`spec-writer.md\` and \`code-reviewer.md\` (always needed)
   - Keep \`gdpr-auditor.md\` if handling user data
   - Keep \`release-manager.md\`

5. **Update README.md:**
   - Set project name, description, and stack
   - Update Quick Start commands for the chosen stack

6. **Decide folder structure:**
   - Based on project type and stack, propose the appropriate structure
   - Create necessary directories (apps/web, services/backend, etc.)
   - Remove unnecessary ones

7. **Delete this file** (\`prompt.md\`) when configuration is complete.

After completing these steps, confirm to the user that the project is ready and run \`/start\` to begin development.
EOF

# ── Rename architect file ──
if [ -f ".opencode/agents/project-architect.md" ]; then
  mv ".opencode/agents/project-architect.md" ".opencode/agents/${ARCHITECT_NAME}.md"
  # Update frontmatter name field
  if command -v sed &> /dev/null; then
    sed -i '' "s/^name: project-architect/name: ${ARCHITECT_NAME}/" ".opencode/agents/${ARCHITECT_NAME}.md" 2>/dev/null || \
    sed -i "s/^name: project-architect/name: ${ARCHITECT_NAME}/" ".opencode/agents/${ARCHITECT_NAME}.md"
  fi
  echo -e "${GREEN}  ✓ Renamed project-architect.md → ${ARCHITECT_NAME}.md${NC}"
fi

# ── Update opencode.json default_agent ──
if command -v sed &> /dev/null; then
  sed -i '' "s/\"default_agent\": \"project-architect\"/\"default_agent\": \"${ARCHITECT_NAME}\"/" .opencode/opencode.json 2>/dev/null || \
  sed -i "s/\"default_agent\": \"project-architect\"/\"default_agent\": \"${ARCHITECT_NAME}\"/" .opencode/opencode.json
  sed -i '' "s/\"default_agent\": \"project-architect\"/\"default_agent\": \"${ARCHITECT_NAME}\"/" .opencode/opencode.jsonc 2>/dev/null || \
  sed -i "s/\"default_agent\": \"project-architect\"/\"default_agent\": \"${ARCHITECT_NAME}\"/" .opencode/opencode.jsonc
fi
echo -e "${GREEN}  ✓ Updated default_agent in opencode.json/jsonc${NC}"

echo ""
echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Setup complete!${NC}"
echo ""
echo -e "  ${YELLOW}Next step:${NC} Open the project in opencode."
echo -e "  The agent will read ${CYAN}prompt.md${NC} and finish configuration."
echo ""
