# init.ps1 - SDD Agent Harness Project Setup
# Interactive script to configure a new project from the template.
# Generates prompt.md for the agent to finish configuration.

$ErrorActionPreference = "Stop"

function Write-Prompt { param($Message) Write-Host $Message -ForegroundColor Cyan }
function Write-Ok { param($Message) Write-Host $Message -ForegroundColor Green }
function Write-Warn { param($Message) Write-Host $Message -ForegroundColor Yellow }
function Write-Err { param($Message) Write-Host $Message -ForegroundColor Red }

Write-Host ""
Write-Prompt "SDD Agent Harness - Project Setup"
Write-Prompt "================================="
Write-Host ""

# -- Project Identity --
Write-Host "Project Identity" -ForegroundColor Green

do {
    $ProjectName = Read-Host "  Project name (kebab-case, e.g. my-app)"
    if ([string]::IsNullOrWhiteSpace($ProjectName)) {
        Write-Err "  Project name is required."
    }
} while ([string]::IsNullOrWhiteSpace($ProjectName))

do {
    $ProjectDesc = Read-Host "  One-line description"
    if ([string]::IsNullOrWhiteSpace($ProjectDesc)) {
        Write-Err "  Description is required."
    }
} while ([string]::IsNullOrWhiteSpace($ProjectDesc))

Write-Host ""
Write-Warn "  Project type:"
Write-Host "    1) web-app"
Write-Host "    2) api"
Write-Host "    3) full-stack"
Write-Host "    4) cli"
Write-Host "    5) mobile"
Write-Host "    6) desktop"
$TypeNum = Read-Host "  Select [1-6] (default: 3)"
switch ($TypeNum) {
    "1" { $ProjectType = "web-app" }
    "2" { $ProjectType = "api" }
    "3" { $ProjectType = "full-stack" }
    "4" { $ProjectType = "cli" }
    "5" { $ProjectType = "mobile" }
    "6" { $ProjectType = "desktop" }
    default { $ProjectType = "full-stack" }
}

Write-Host ""
Write-Warn "  UI language:"
Write-Host "    1) English"
Write-Host "    2) Spanish"
Write-Host "    3) Multi-language"
$LangNum = Read-Host "  Select [1-3] (default: 1)"
switch ($LangNum) {
    "1" { $UiLang = "English" }
    "2" { $UiLang = "Spanish" }
    "3" { $UiLang = "Multi-language" }
    default { $UiLang = "English" }
}

# -- Stack --
Write-Host ""
Write-Host "Stack" -ForegroundColor Green

Write-Host ""
Write-Warn "  Frontend framework:"
Write-Host "    1) Next.js"
Write-Host "    2) Astro"
Write-Host "    3) React (Vite)"
Write-Host "    4) Vue"
Write-Host "    5) Svelte"
Write-Host "    6) None (no frontend)"
$FeNum = Read-Host "  Select [1-6] (default: 1)"
switch ($FeNum) {
    "1" { $Frontend = "Next.js" }
    "2" { $Frontend = "Astro" }
    "3" { $Frontend = "React (Vite)" }
    "4" { $Frontend = "Vue" }
    "5" { $Frontend = "Svelte" }
    "6" { $Frontend = "None" }
    default { $Frontend = "Next.js" }
}

Write-Host ""
Write-Warn "  Backend technology:"
Write-Host "    1) Node/Express"
Write-Host "    2) Python/FastAPI"
Write-Host "    3) PocketBase"
Write-Host "    4) Supabase"
Write-Host "    5) Go"
Write-Host "    6) Rust"
Write-Host "    7) None (no backend)"
$BeNum = Read-Host "  Select [1-7] (default: 1)"
switch ($BeNum) {
    "1" { $Backend = "Node/Express" }
    "2" { $Backend = "Python/FastAPI" }
    "3" { $Backend = "PocketBase" }
    "4" { $Backend = "Supabase" }
    "5" { $Backend = "Go" }
    "6" { $Backend = "Rust" }
    "7" { $Backend = "None" }
    default { $Backend = "Node/Express" }
}

Write-Host ""
Write-Warn "  Database:"
Write-Host "    1) PostgreSQL"
Write-Host "    2) SQLite"
Write-Host "    3) MongoDB"
Write-Host "    4) None (no database)"
$DbNum = Read-Host "  Select [1-4] (default: 1)"
switch ($DbNum) {
    "1" { $Database = "PostgreSQL" }
    "2" { $Database = "SQLite" }
    "3" { $Database = "MongoDB" }
    "4" { $Database = "None" }
    default { $Database = "PostgreSQL" }
}

Write-Host ""
Write-Warn "  Deploy platform:"
Write-Host "    1) Docker"
Write-Host "    2) Vercel"
Write-Host "    3) Coolify"
Write-Host "    4) Railway"
Write-Host "    5) Manual"
$DepNum = Read-Host "  Select [1-5] (default: 1)"
switch ($DepNum) {
    "1" { $Deploy = "Docker" }
    "2" { $Deploy = "Vercel" }
    "3" { $Deploy = "Coolify" }
    "4" { $Deploy = "Railway" }
    "5" { $Deploy = "Manual" }
    default { $Deploy = "Docker" }
}

# -- Generate prompt.md --
Write-Host ""
Write-Prompt "================================="
Write-Ok "Generating prompt.md..."

$ArchitectName = "$ProjectName-architect"
$StackSummary = "$Frontend + $Backend + $Database"

$PromptContent = @"
# Project Configuration - Generated by init.ps1

## Project Identity
- **Name:** $ProjectName
- **Description:** $ProjectDesc
- **Type:** $ProjectType
- **UI Language:** $UiLang

## Stack
- **Frontend:** $Frontend
- **Backend:** $Backend
- **Database:** $Database
- **Deploy:** $Deploy
- **Stack Summary:** $StackSummary

## Agent Configuration
- **Architect Name:** $ArchitectName

---

## Instructions for Agent

Read this file and execute the following steps:

1. **Update architect agent:**
   - Update the frontmatter name field in .opencode/agents/$ArchitectName.md to $ArchitectName
   - Update any references to project-architect in the file body

2. **Update AGENTS.md:**
   - Fill header placeholders: PROJECT_NAME, ONE_LINE_DESCRIPTION, STACK_TECH, DATE
   - Update the architect name in the Agent Harness table
   - Update the Project Clarification examples if needed

3. **Update opencode config:**
   - Set default_agent to $ArchitectName in both opencode.json and opencode.jsonc

4. **Configure agents for this stack:**
   - If Frontend is "None": delete frontend-developer.md
   - If Backend is "None": delete backend-developer.md
   - Keep spec-writer.md and code-reviewer.md (always needed)
   - Keep gdpr-auditor.md if handling user data
   - Keep release-manager.md

5. **Update README.md:**
   - Set project name, description, and stack
   - Update Quick Start commands for the chosen stack

6. **Decide folder structure:**
   - Based on project type and stack, propose the appropriate structure
   - Create necessary directories (apps/web, services/backend, etc.)
   - Remove unnecessary ones

7. **Delete this file (prompt.md) when configuration is complete.**

After completing these steps, confirm to the user that the project is ready and run /start to begin development.
"@

Set-Content -Path "prompt.md" -Value $PromptContent -Encoding UTF8

# -- Rename architect file --
$OldArchitect = ".opencode\agents\project-architect.md"
$NewArchitect = ".opencode\agents\$ArchitectName.md"

if (Test-Path $OldArchitect) {
    Move-Item -LiteralPath $OldArchitect -Destination $NewArchitect -Force
    $Content = Get-Content -LiteralPath $NewArchitect -Raw
    $Content = $Content -replace "name: project-architect", "name: $ArchitectName"
    Set-Content -LiteralPath $NewArchitect -Value $Content -Encoding UTF8 -NoNewline
    Write-Ok "  Renamed project-architect.md to $ArchitectName.md"
}

# -- Update opencode.json default_agent --
$Files = @(".opencode/opencode.json", ".opencode/opencode.jsonc")
foreach ($File in $Files) {
    if (Test-Path $File) {
        $Content = Get-Content -LiteralPath $File -Raw
        $OldVal = 'project-architect'
        $Content = $Content -replace $OldVal, $ArchitectName
        Set-Content -LiteralPath $File -Value $Content -Encoding UTF8 -NoNewline
    }
}
Write-Ok "  Updated default_agent in opencode.json/jsonc"

Write-Host ""
Write-Prompt "================================="
Write-Ok "Setup complete!"
Write-Host ""
Write-Warn "  Next step: Open the project in opencode."
Write-Host "  The agent will read prompt.md and finish configuration."
Write-Host ""
